parameters:
    callouts:
        signup_multiple_center_success:
            highlight: "Your account has been created!"
            subText: "You can either complete your profile using the guide below, or start adding your clinics or departments. We recommend that you complete the steps below to ensure that you are providing patients with complete and updated information about what your institution offers."
        login_complete_profile:
            highlight: "Welcome back {FIRST_NAME}!"
            subText: "Now, let's give your patients a way to contact and find you."
        login_incomplete_profile_singleCenter:
            highlight: "Welcome back {FIRST_NAME}! Please take time to complete your clinic profile:"
        login_incomplete_profile_multipleCenter:
            highlight: "Welcome back {FIRST_NAME}! Please take time to complete your profile:"
        success_add_center:
            highlight: "Your Clinic {CENTER_NAME} has been added! Review the clinic information below or <a href={ADD_CLINIC_URL}>Add another Clinic >></a> "
        success_edit_center:
            highlight: "Your edits to {CENTER_NAME} have been saved! Review the clinic information below or <a href={ADD_CLINIC_URL}>Add another Clinic >></a>"
