institution_userType_index:
    pattern: /staff/designations
    defaults: { _controller: InstitutionBundle:InstitutionUserType:index }
    requirements:    
        _method:  GET
institution_userType_add:
    pattern: /staff/designations/add
    defaults: { _controller: InstitutionBundle:InstitutionUserType:add }
    requirements:    
        _method:  GET

institution_userType_add_save:
    pattern: /staff/designations/add
    defaults: { _controller: InstitutionBundle:InstitutionUserType:save }
    requirements:    
        _method:  POST
        id: \d+
        
institution_userType_edit:
    pattern: /staff/designations/edit/{id}
    defaults: { _controller: InstitutionBundle:InstitutionUserType:edit }
    requirements:    
        _method:  GET
        
institution_userType_edit_save:
    pattern: /staff/designations/edit/{id}
    defaults: { _controller: InstitutionBundle:InstitutionUserType:save }
    requirements:    
        _method:  POST
        id: \d+

