parameters:    

    local_web_root: %kernel.root_dir%/../web
    media_source: local
    
    mailchimp_api_key: c92eb834bde4ae8c737d7de468ee9f4e-us6
    mailchimp_connection: http

    site_url: http://www.healthcareabroad.com
    site_name: MEDtrip.com
    domain_name: healthcareabroad.com

    cfe_site_url: http://www.chromedia.com
    cfe_site_name: www.Chromedia.com
    cfe_company_name: Chromedia Far East Inc.

    ## TinyMCE theme params
    tinymce_textarea_class: "tinymce"

    tinymce_simple_theme:
        width: 470
        height: 150
        mode: "textareas"
        theme: "advanced"
        setup: "tinymceSetup"
        forced_root_block: ""
        paste_text_sticky: true,
        paste_text_sticky_default: true,
        #theme_advanced_buttons1: "mylistbox,mysplitbutton,bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,bullist,numlist,undo,redo,link,unlink"
        theme_advanced_buttons1: "bullist,numlist"
        theme_advanced_buttons2: ""
        theme_advanced_buttons3: ""
        theme_advanced_toolbar_location: "top"
        theme_advanced_toolbar_align: "left"
        theme_advanced_statusbar_location : false
        plugins: "paste"
        theme_advanced_buttons1_add: "fullscreen"

    tinymce_advanced_theme:
        theme: "advanced"
        plugins: "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template"
        theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect"
        theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor"
        theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen"
        theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak"
        theme_advanced_toolbar_location: "top"
        theme_advanced_toolbar_align: "left"
        theme_advanced_statusbar_location: "bottom"
        theme_advanced_resizing: true
        
    tinymce_medium_theme:
        mode: "textareas"
        theme: "advanced"
        plugins: "table,advhr,advlink,paste,xhtmlxtras,spellchecker"
        theme_advanced_buttons1: "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,forecolor,backcolor,|,hr,removeformat,|,sub,sup,|,spellchecker"
        theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,bullist,numlist,|,undo,redo,|,link,unlink,anchor,cleanup,code,|,tablecontrols"
        theme_advanced_buttons3: ""
        theme_advanced_toolbar_location: "top"
        theme_advanced_toolbar_align: "left"
        theme_advanced_statusbar_location: ""
        paste_auto_cleanup_on_paste: true
        spellchecker_languages: "+English=en,Dutch=nl"
        
    tinymce_bbcode_theme:
        mode: "none"
        theme: "advanced"
        plugins: "bbcode"
        theme_advanced_buttons1: "bold,italic,underline,undo,redo,link,unlink,image,forecolor,styleselect,removeformat,cleanup,code"
        theme_advanced_buttons2: ""
        theme_advanced_buttons3: ""
        theme_advanced_toolbar_location: "bottom"
        theme_advanced_toolbar_align: "center"
        theme_advanced_styles: "Code=codeStyle;Quote=quoteStyle"
        entity_encoding: "raw"
        add_unload_trigger: false
        remove_linebreaks: false
        inline_styles: false
        convert_fonts_to_spans: false

    imageplaceholder:
        specializationDefaultLogo: /images/institution/default-specialization-logo.png
        institutionFeaturedImage: /images/default-hospital-featured-image.png 
        institutionDefaultLogo: /images/institution/default-hospital-logo.png
        doctorDefaultImage: /images/institution/default-doctor-icon.png
        imcDefaultLogo: /images/institution/default_clinic.png
        destinationIcon: ''
        loading: /images/institution/spinner_large.gif


    amazonS3_key: AKIAIAZVLNMMNLBC6IEA
    amazonS3_secret: 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
    amazonS3_bucket_name: assets.healthcareabroad.com 

    media_directory: media
    media_advertisement_subdir: %media_directory%/features
    media_doctor_subdir: %media_directory%/doctors
    media_institution_subdir: %media_directory%/institutions
    media_specialization_subdir: %media_directory%/specializations


    # Media Context are the filesystems 
    # NOTE: When Adding new filesystem, it MUST be added here to.
    media_context:
        advertisement: advertisement
        institution: institution
        specialization: specialization
        doctor: doctor